spring:
  h2:
    console:
      enabled: true
      path: /h2-console #http://localhost:8080/h2-console
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %replace(%m%wEx{6}){'[\r\n]+', '\\\\n'}%nopex%n}"
  level:
    org.springframework: debug
